import com.sun.xml.internal.bind.v2.runtime.unmarshaller.XsiNilLoader;
import java.util.Random;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kausik N
 */
public class Maze_BasicGen_BasicGUI extends javax.swing.JFrame {

    /**
     * Creates new form Maze_BasicGen_BasicGUI
     */
    public Maze_BasicGen_BasicGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background_Panel = new javax.swing.JPanel();
        Back_Label = new javax.swing.JLabel();
        Title_Label = new javax.swing.JLabel();
        Left_Label = new javax.swing.JLabel();
        Right_Label = new javax.swing.JLabel();
        Front_Label = new javax.swing.JLabel();
        Left_Button = new javax.swing.JButton();
        Front_Button = new javax.swing.JButton();
        Back_Button = new javax.swing.JButton();
        Right_Button = new javax.swing.JButton();
        GenerateMaze_Button = new javax.swing.JButton();
        SolutionMaze_Button = new javax.swing.JButton();
        RestartMaze_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background_Panel.setBackground(new java.awt.Color(0, 0, 0));

        Back_Label.setBackground(new java.awt.Color(102, 0, 0));
        Back_Label.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        Back_Label.setForeground(new java.awt.Color(0, 255, 204));
        Back_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Back_Label.setText("B");
        Back_Label.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));

        Title_Label.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        Title_Label.setForeground(new java.awt.Color(0, 255, 204));
        Title_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title_Label.setText("MAZE RUNNER");

        Left_Label.setBackground(new java.awt.Color(102, 0, 0));
        Left_Label.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        Left_Label.setForeground(new java.awt.Color(0, 255, 204));
        Left_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Left_Label.setText("L");
        Left_Label.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));

        Right_Label.setBackground(new java.awt.Color(102, 0, 0));
        Right_Label.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        Right_Label.setForeground(new java.awt.Color(0, 255, 204));
        Right_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Right_Label.setText("R");
        Right_Label.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));

        Front_Label.setBackground(new java.awt.Color(102, 0, 0));
        Front_Label.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        Front_Label.setForeground(new java.awt.Color(0, 255, 204));
        Front_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Front_Label.setText("F");
        Front_Label.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));

        Left_Button.setBackground(new java.awt.Color(0, 0, 0));
        Left_Button.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Left_Button.setForeground(new java.awt.Color(0, 204, 204));
        Left_Button.setText("Go");
        Left_Button.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 204, 204)));

        Front_Button.setBackground(new java.awt.Color(0, 0, 0));
        Front_Button.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Front_Button.setForeground(new java.awt.Color(0, 204, 204));
        Front_Button.setText("Go");
        Front_Button.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 204, 204)));

        Back_Button.setBackground(new java.awt.Color(0, 0, 0));
        Back_Button.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Back_Button.setForeground(new java.awt.Color(0, 204, 204));
        Back_Button.setText("Go");
        Back_Button.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 204, 204)));

        Right_Button.setBackground(new java.awt.Color(0, 0, 0));
        Right_Button.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Right_Button.setForeground(new java.awt.Color(0, 204, 204));
        Right_Button.setText("Go");
        Right_Button.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 204, 204)));

        GenerateMaze_Button.setBackground(new java.awt.Color(0, 0, 0));
        GenerateMaze_Button.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        GenerateMaze_Button.setForeground(new java.awt.Color(0, 204, 204));
        GenerateMaze_Button.setText("Generate New Maze");
        GenerateMaze_Button.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 204, 204)));
        GenerateMaze_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateMaze_ButtonActionPerformed(evt);
            }
        });

        SolutionMaze_Button.setBackground(new java.awt.Color(0, 0, 0));
        SolutionMaze_Button.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        SolutionMaze_Button.setForeground(new java.awt.Color(0, 204, 204));
        SolutionMaze_Button.setText("Solution");
        SolutionMaze_Button.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 204, 204)));

        RestartMaze_Button.setBackground(new java.awt.Color(0, 0, 0));
        RestartMaze_Button.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        RestartMaze_Button.setForeground(new java.awt.Color(0, 204, 204));
        RestartMaze_Button.setText("Restart Maze");
        RestartMaze_Button.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 204, 204)));

        javax.swing.GroupLayout Background_PanelLayout = new javax.swing.GroupLayout(Background_Panel);
        Background_Panel.setLayout(Background_PanelLayout);
        Background_PanelLayout.setHorizontalGroup(
            Background_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Background_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Background_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Background_PanelLayout.createSequentialGroup()
                        .addComponent(Left_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Front_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(256, 256, 256)
                        .addComponent(Right_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Background_PanelLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(Background_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Background_PanelLayout.createSequentialGroup()
                                .addComponent(Title_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(356, 356, 356))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Background_PanelLayout.createSequentialGroup()
                                .addGroup(Background_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Front_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(Background_PanelLayout.createSequentialGroup()
                                        .addGroup(Background_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Left_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(Background_PanelLayout.createSequentialGroup()
                                                .addGap(96, 96, 96)
                                                .addComponent(GenerateMaze_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                                        .addGroup(Background_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Back_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(SolutionMaze_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(Background_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Background_PanelLayout.createSequentialGroup()
                                        .addGap(261, 261, 261)
                                        .addComponent(Right_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(Background_PanelLayout.createSequentialGroup()
                                        .addGap(104, 104, 104)
                                        .addComponent(RestartMaze_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(61, 61, 61))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Background_PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Back_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(449, 449, 449))
        );
        Background_PanelLayout.setVerticalGroup(
            Background_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Background_PanelLayout.createSequentialGroup()
                .addComponent(Title_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(Background_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Background_PanelLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(Right_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Right_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Background_PanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Front_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Front_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(Back_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Background_PanelLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(Left_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Left_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Back_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(Background_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenerateMaze_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SolutionMaze_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RestartMaze_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Background_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Background_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Random random = new Random();
    
    public class PathTreeNode
    {
        // Node Properties
        String id;
        int no_of_children;
        PathTreeNode[] children;
        PathTreeNode parent;
        // Node Properties
        
        public PathTreeNode(String id_param, int no_of_children_param, PathTreeNode[] children_param, PathTreeNode parent_param)
        {
            id = id_param;
            no_of_children = no_of_children_param;
            if(children_param != null)
            { 
                children = new PathTreeNode[children_param.length];
                System.arraycopy(children_param, 0, children, 0, children_param.length);
            }
//            if(children_param != null)
//            {
//                children = new PathTreeNode[children_param.length];
//                for(int i=0;i<children_param.length;i++)
//                {
//                    children[i] = children_param[i];
//                }
//            }
            else children = null;
            parent = parent_param;
        }
    }
    
    public class PathTree
    {
        // Params
        int max_tree_depth;                      // Maximum depth of the maze -- height of pathtree
        
        float dead_end_probability;         // Probability that the current node can be a dead end -- no branches
        
        int max_branches;                   // Maximum number of branches in current node
        float branch_formation_probability; // Probability that the current branch is formed in current node -- whether the branch will exist or not for the node
        float cycle_formation_probability;  // Probability that the current branch of the current node connects to a preexisting node -- forming a cycle
        //Params
        
        // Tree
        PathTreeNode RootNode;
        int current_tree_depth;
        // Tree
        
        
        public PathTree()
        {
            
        }
        
        void InitPathTreeParameters(int max_tree_depth_param, float dead_end_probability_param, int max_branches_param, float branch_formation_probability_param, float cycle_formation_probability_param)
        {
            max_tree_depth = max_tree_depth_param;
            dead_end_probability = dead_end_probability_param;
            max_branches = max_branches_param;
            branch_formation_probability = branch_formation_probability_param;
            cycle_formation_probability = cycle_formation_probability_param;
        }
        
        void GeneratePathTree()
        {
            current_tree_depth = 0;
            RootNode = GeneratePathTree_Recursive("1", null, 0);
        }
        
        PathTreeNode GeneratePathTree_Recursive(String id, PathTreeNode parent, int depth)
        {
            if(depth <= max_tree_depth)
            {
                int no_of_children = 0;
                int[] children_present = GenerateChildren();    // if null - dead end || if 1 - child at position present || if 0 - child at position not present
                // Dead End
                if(children_present == null)
                {
                    PathTreeNode newNode = new PathTreeNode(id, 0, new PathTreeNode[max_branches], parent);
                    for(int i=0;i<max_branches;i++)
                    {
                        newNode.children[i] = null;
                    }
                    return newNode;
                }
                // Non Dead End
                for(int i=0;i<max_branches;i++)
                {
                    if(children_present[i] == 1) no_of_children = no_of_children + 1;
                }

                PathTreeNode newNode = new PathTreeNode(id, no_of_children, new PathTreeNode[max_branches], parent);
                for(int i=0;i<max_branches;i++)
                {
                    if(children_present[i] == 1)
                    { 
                        if(random.nextInt(100 + 1) <= (cycle_formation_probability*100))
                        {
                            newNode.children[i] = GetCycleDestinationNode(id + "_" + i);
                        }
                        else newNode.children[i] = GeneratePathTree_Recursive(id + "_" + i, newNode, depth+1);
                    }
                    else newNode.children[i] = null;
                }
                current_tree_depth = current_tree_depth + 1;
                return newNode;
            }
            return null;
        }
        
        int[] GenerateChildren()
        {
            // Check for Dead End
            if(random.nextInt(100 + 1) <= (dead_end_probability*100))
            {
                return null;
            }
            else
            {
                int[] child_present = new int[max_branches];
                for(int i=0;i<max_branches;i++)
                {
                    if(random.nextInt(100 + 1) <= (branch_formation_probability*100))
                    {
                        child_present[i] = 1;
                    }
                    else child_present[i] = 0;
                }
                return child_present;
            }
        }
        
        PathTreeNode GetCycleDestinationNode(String id)
        {
            PathTreeNode CurrentNode = RootNode;
            int random_depth = random.nextInt(max_tree_depth) + 1;
            while(random_depth > 0)
            {
                int random_child = random.nextInt(CurrentNode.no_of_children + 1);
                for(int i=0;i<max_branches;i++)
                {
                    if(CurrentNode.children[i] != null)
                    {
                        random_child = random_child - 1;
                        if(random_child == 0)
                        {
                            if(CurrentNode.children[i].id.equals(id)) return CurrentNode;   // If going to same node change to the parent instead -- node cant go to same node
                            
                            CurrentNode = CurrentNode.children[i];
                            i = max_branches;   // BREAK
                        }
                    }
                }
                random_depth = random_depth - 1;
            }
            return CurrentNode;
        }
        
        
        void DisplayPathTree(PathTreeNode p, int depth)
        {
            if(p != null)
            {
                System.out.println(depth + " - " + p.id);
                for(int i=0;i<max_branches;i++)
                {
                    if(p.children[i] != null)
                    {
                        DisplayPathTree(p.children[i], depth + 1);
                    }
                }
            }
        }
    }
    
    PathTree Maze;
    
    private void GenerateMaze_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateMaze_ButtonActionPerformed
    Maze = new PathTree();
    Maze.InitPathTreeParameters(2, 0.5f, 3, 0.5f, 0.0f);
    
    Maze.GeneratePathTree();
    
    System.out.println("Displaying Path Tree...");
    Maze.DisplayPathTree(Maze.RootNode, 1);
    }//GEN-LAST:event_GenerateMaze_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Maze_BasicGen_BasicGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Maze_BasicGen_BasicGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Maze_BasicGen_BasicGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Maze_BasicGen_BasicGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Maze_BasicGen_BasicGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_Button;
    private javax.swing.JLabel Back_Label;
    private javax.swing.JPanel Background_Panel;
    private javax.swing.JButton Front_Button;
    private javax.swing.JLabel Front_Label;
    private javax.swing.JButton GenerateMaze_Button;
    private javax.swing.JButton Left_Button;
    private javax.swing.JLabel Left_Label;
    private javax.swing.JButton RestartMaze_Button;
    private javax.swing.JButton Right_Button;
    private javax.swing.JLabel Right_Label;
    private javax.swing.JButton SolutionMaze_Button;
    private javax.swing.JLabel Title_Label;
    // End of variables declaration//GEN-END:variables
}
